name: JS Actions

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Leave a comment
        uses: ./.github/actions/joke-action
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issueNumber: 1

